Page Structure
er-contreras/leaderboard pull request #1
Opened 2021-08-03 16:46 UTC by eri8-9

- Create an npm project with Webpack.

2021-08-03 21:05 UTC, henatan99 requested changes
Hi @eri8-9 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

- [x] You did not configure the GitHub workflows linters file so linter checks are not showing in your github repo. Kindly fix this.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-03 21:05 UTC, henatan99 commented on src/index.js
> +import './style.css';
- [x] You should construct your DOM elements here. But it looks your index.js is empty. Please make the required changes here.

2021-08-03 21:05 UTC, henatan99 commented on package.json
> +  },
- [ ] Your package.json scripts miss the `start` key. You app should run with `npm start` or `npm run start` command.

2021-08-04 01:47 UTC, Davidosky007 requested changes
# Hi @eri8-9 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-04 01:47 UTC, Davidosky007 commented on src/index.js
> +function htmlContent() {
* In this project you are encouraged to use ES6 syntax (ie arrow function) [Refer to Project requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/leaderboard/m1_basic_structure.md#:~:text=using%20webpack%20and%20ES6%20features%2C) i suggest you replace the `function` keyword with `arrow function` as it is a requirement for this project

2021-08-04 15:10 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @eri8-9  🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

![Well done team](https://user-images.githubusercontent.com/60631456/128206077-33740bc8-158b-40b1-b35f-afecbabfac43.gif)

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-04 15:12 UTC, merged